### ISSUE TITLE
Impossible de la désactiver

### ISSUE THREAD

**Issue by ghost** [Parow/prw_radio#2]
Salut, je te préviens seulement que lorsque l'on utilise la radio, si nous la désactivons, les personnes avec qui l'ont était connectés nous entendent encore, même si l'on change de fréquence ou que l'on désactive la radio.

Merci de ton travail en tout cas, tu gère x)

**Comment by Parow** [comment]
Désolé de pas avoir répondu plus tot je n'avais pas vu, test le dernier fix il résous le bugs des fréquences
